### ISSUE TITLE
Seems not compatible with Gantt ?

### ISSUE THREAD

**Issue by Moyf** [gitcpy/mermaid-zoom-drag#4]
Hi, I used the plugin and it seems that it can not view (Zoom) the Gantt mermaid

**Comment by Moyf** [comment]
Oh， after refreshing the page it works!

**Comment by gitcpy** [comment]
Great， enjoy it!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/mermaid-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月10日(星期二) 下午4:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Seems not compatible with Gantt ? (Issue #4)





 
Oh， after refreshing the page it works!

**Comment by Moyf** [comment]
> Great， enjoy it!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/mermaid-zoom-drag" ***@***.***&gt;; 发送时间:&nbsp;2024年9月10日(星期二) 下午4:04 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [gitcpy/mermaid-zoom-drag] Seems not compatible with Gantt ? (Issue #4) Oh， after refreshing the page it works! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

This plugin is really useful! I've been loving it for quite some time now. Haha! :D
